# @format

name: Testing

on:
  push:
    branches:
      - 'master'

jobs:
  main:
    name: NPM Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@latest
