# @format

name: Testing

on:
  push:
    branches:
      - 'master'

jobs:
  main:
    name: NPM Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node v20
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm i

      - name: Build Package
        run: npm run build

      - name: Passing checks
        run: echo All checks passed!
